site_name: MMI ORR
repo_url: https://github.com/mmisw/mmiorr-docs
theme:
  name: material
  logo: https://mmisw.org/logo-sm.png

extra:
  analytics:
    provider: google
    property: UA-16970585-1

markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: True
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
- Home: index.md
- About: about.md
- Introduction: introduction.md
- Semantic Web Basics: semweb.md
- Getting Started: gettingstarted.md
- FAQ: faq.md
- Searching and Querying:
  - Finding ontologies and terms in the GUI: search.md
  - Querying via REST API: api/query.md
  - Querying via SPARQL API: query.md
- Working with Vocabularies:
  - Creating a Vocabulary: vocab/new.md
  - Importing a Vocabulary: vocab/import.md
  - Viewing a Vocabulary: vocab/view.md
  - Updating a Vocabulary: vocab/newversion.md
  - Registering a Vocabulary: vocab/register.md
- Working with Ontologies:
  - Registering Your Existing Ontology: ontology/new.md
  - Updating an Ontology: ontology/newversion.md
- Working with Mappings:
  - Creating a Mapping Ontology: mapping/new.md
  - Updating a Mapping Ontology: mapping/newversion.md
- Changes: changes.md
- From v2 to v3: from2to3.md
- Advanced Topics:
  - REST API: api/index.md
  - Administration: admin/index.md
  - Known issues: issues.md
  - Installation: install/index.md
